### ISSUE TITLE
The `body` option from `got` does not work at all

### ISSUE THREAD

**Issue by mnmkng** [apify/got-scraping#11]
This code does not send the body at all. It also does not work with the `json` option. I haven't tested with `form`, but I assume it will be the same.

```js
const got = require('got-scraping');

got({
    url: 'https://en2ydmzx2ein.x.pipedream.net/',
    body: '{ foo: "bar" }',
    method: 'POST',
    ciphers: undefined,
}).then((res) => {
    console.dir(res);
});
```

If you replace the `require` with `got`, it works fine. The above code also does not fail when the `method: 'POST'` is removed. Whereas in `got` it throws

```
RequestError: The `GET` method cannot be used with a body
```

**Comment by petrpatek** [comment]
This is super weird, when got-scraping modifies options it is done using `https://github.com/sindresorhus/got#gotmergeoptionsparent-sources`, which should not merge `body`, `json` or `formdata` - however it should replace those with the new values if provided as in the example in docs. On top of that we are using `got.extend`, which should produce exactly the same interface/behavior as got 🤷‍♂️ . However, as we have seen before with the async stream - it can vary 😞.

**Comment by petrpatek** [comment]
One more note to this. This package is made for document get requests because of the header generation. If anyone is making a POST request, the headers will vary (a lot) from the GET request's headers.

**Comment by mnmkng** [comment]
Yeah, but sometimes you need to send `POST` requests to websites. Typically those using `aspx` and other old stuff to navigate. So we need to support it at least on the "can make the request" level. Even though the headers might be a bit wonky. There are a lot of users who use `POST` in their scrapers. We can start collecting `POST` headers later in the collector.
