### ISSUE TITLE
Possible to set timeout for ALPN in browser-headers hook

### ISSUE THREAD

**Issue by Qvaza** [apify/got-scraping#130]
Currently we're experiencing issues where the resolveProtocol promise never resolves in the browser-headers hook, due to no timeout being set. Should it reuse the timeout set in the timeout.lookup in request options?

**Comment by barjin** [comment]
Hello and thank you for your interest in this package!

Could you please share the URL where you experienced this / some reproduction scenario? All parts of the request processing should indeed respect the respective timeouts, so this is a potential issue - but we would still want to see it happening before we try to fix it :)

Cheers!

**Comment by Qvaza** [comment]
A site like https://www.cyclebrother.com should reproduce the error, where the server does not respond.

Setting a request timeout or lookup timeout, is not respected in the browser-headers hook

`await gotScraping.get({ url: "https://www.cyclebrother.com", timeout: { request: 5000, lookup: 2000 } })`

Got around it by just setting our own resolveProtocol in the options object
