### ISSUE TITLE
getaddrinfo EAI_AGAIN undefined

### ISSUE THREAD

**Issue by Cooya** [apify/got-scraping#135]
Since a few days I get this error "getaddrinfo EAI_AGAIN undefined" for any URL with got-scraping, I cannot use it anymore. It works fine when I switch to fetch. Any idea why I suddenly get this ? Is it coming from a misconfiguration in my OS (Ubuntu 20) ?

**Comment by Cooya** [comment]
My mistake, I put a bad URL in the proxy configuration. Sorry to have bothered you.

**Comment by barjin** [comment]
Ah, no worries. Maybe we should communicate this more transparently on our side - thank you for the report either way!
