### ISSUE TITLE
Is it possible to set http2 fingerprint?

### ISSUE THREAD

**Issue by tocha688** [apify/got-scraping#144]
https://tools.scrapfly.io/api/fp/anything

Here you can see the browser's http2 fingerprint. Can we use this library to process http2 fingerprint? It is similar to the following library, but it is in go language
https://github.com/gospider007/requests

**Comment by barjin** [comment]
Hello, and thank you for your interest in this Actor!

Unfortunately, no - as far as we know, it would not be feasible to modify the internals of the HTTP2 (or TLS...) protocols in a Node library. We are aware of the increasing use of JA3 and similar fingerprinting methods online and are currently looking for a better solution.

However, I'll have to close this issue as there isn't much we can do with got-scraping in this regard.
Thank you for your understanding!
