### ISSUE TITLE
URLs for testing

### ISSUE THREAD

**Issue by Kikobeats** [apify/got-scraping#34]
I'm trying to targetting https://techblog.willshouse.com/2012/01/03/most-common-user-agents/ without success.

Any top for getting the content behind CloudFlare DDoS?

**Comment by mnmkng** [comment]
For CloudFlare, it's generally easier to use a browser. Especially if you only need to do one request.

**Comment by Kikobeats** [comment]
That's right but being the purpose of the library to "send browser-like requests" I hope something in that direction could be done

**Comment by mnmkng** [comment]
Like any other anti-bot provider, CloudFlare uses a scoring mechanism. It's up to the user of CloudFlare to set the threshold. It uses a combination of factors such as IP reputation, request signature and also sends HTML with JavaScript challenges. This package can help with the request signature part. IP rep depends on the proxies you use. JS challenges are out of scope of this package.

**Comment by szmarczak** [comment]
We could potentially use JSDOM and enable JavaScript execution there but that won't work because the challenges call APIs that aren't implemented in JSDOM. It's better if you manually process the challenges.

**Comment by JaneJeon** [comment]
For what it's worth, it's been working for me even with a known datacenter IP. I @Kikobeats I think using a residential IP (or an IP with better "reputation") would be the next step
