### ISSUE TITLE
Giving proxyUrl with a password that contains special characters crashes

### ISSUE THREAD

**Issue by jirimoravcik** [apify/got-scraping#55]
e.g. having `proxyUrl = 'http://username:a6%6qgx12345@127.0.0.1:8888'` 
will throw `Uncaught URIError: URI malformed` (see https://github.com/apify/got-scraping/blob/master/src/agent/h1-proxy-agent.ts#L21)
I think it should work even with such passwords

ref https://github.com/sindresorhus/got/issues/1317

**Comment by szmarczak** [comment]
This is correct, `%6q` is malformed. You need to [percent-encode](https://en.wikipedia.org/wiki/Percent-encoding) `%` as `%25`:

```
http://username:a6%256qgx12345@127.0.0.1:8888
```
