### ISSUE TITLE
send post request

### ISSUE THREAD

**Issue by i-CNNN** [apify/got-scraping#74]
error code: ERR_SSL_WRONG_VERSION_NUMBER

![image](https://user-images.githubusercontent.com/24954758/182150328-83b295aa-ccb3-48aa-85ee-e443ea1bcc10.png)

**Comment by i-CNNN** [comment]
code like this:
```js
const { gotScraping } = require('got-scraping');
gotScraping({
  url ,
  body,
  method: 'POST',
  headers: { referer: referer, cookie,'content-type': 'application/x-www-form-urlencoded' },
}).then((res ) => {
  console.log(res)
});

```

**Comment by szmarczak** [comment]
tip: do not blur, use a black rectangle - I can perfectly read everything that you have blurred. Blurs are evil :)

---

Looks like you're trying to connect to a HTTP website via HTTPS, hence the TLS error. Try changing the protocol in `url` to `http:`
