### ISSUE TITLE
Using proxyUrl, always goes with timeout

### ISSUE THREAD

**Issue by MLKiiwy** [apify/got-scraping#78]
I try to use one free proxy from https://www.free-proxy-list.com/ to test the package.

But each time I set a `proxyUrl` I have a ETIMEDOUT request error. 
I have tried many different proxies and always got the same error. 

I'm doing my test locally, and the format I use for the proxy is (for example)
```
proxyUrl: 'https://177.36.200.52:8080'
```

If someone has already got this kind of problem?

**Comment by razorcell** [comment]
The format is good, you probably have a bad list.

The [agent](https://github.com/sindresorhus/got/blob/ae04c0e36cf3f5b2e356df7d48a5b19988f935a2/documentation/2-options.md#agent) parameter from **got** does not seem to work in got scraping. the proxyUrl parameter is working fine, i was wondering if i could use the `got.agent` to apply a socks5 tor proxy, i tried this but did not work. what ever i put in the `agent : {http, https, http2}`. The request gets sent to the target directly without using the proxy.

**Comment by szmarczak** [comment]
`agent` is only overridden when `proxyUrl` is set:

https://github.com/apify/got-scraping/blob/15744b41a11a97069d232deeccd25d97e597dc6b/src/hooks/proxy.ts#L18-L23

can you post a repor please?
