### ISSUE TITLE
got-scraping error code 1020 against Cloudflare

### ISSUE THREAD

**Issue by LucasEduardo122** [apify/got-scraping#79]
After the latest updates, I noticed that the scrap simply stopped working with cloudflare, always returning me error code 1020. How to fix it?

**Comment by szmarczak** [comment]
> After the latest updates

What updates?

> the scrap simply stopped working with cloudflare

How do I reproduce this?

**Comment by LucasEduardo122** [comment]
It's been taken care of. Looks like the user-agent was being sent the wrong way.
