### ISSUE TITLE
got-scraping uses deprecated `header-generator`

### ISSUE THREAD

**Issue by jirimoravcik** [apify/got-scraping#89]
We should switch to `fingerprint-suite`

**Comment by barjin** [comment]
Thanks for bringing this up! Now, this is more on us - while the [apify/header-generator](https://github.com/apify/header-generator) repo is deprecated and all the source code is stored in the [fingerprint-suite](https://github.com/apify/fingerprint-suite) monorepo, the packages are still published to npm separately, under their original names. The dependency of `header-generator` is therefore completely fine and installs the latest version of the tool.
