### ISSUE TITLE
Pass host and referer header to the generator

### ISSUE THREAD

**Issue by petrpatek** [apify/got-scraping#9]
In order to ensure the correct order of user-provided headers `referer`. The host should be added automatically by got.

**Comment by mnmkng** [comment]
@szmarczak Do you think this is solved by https://github.com/apify/header-generator/pull/13?

**Comment by szmarczak** [comment]
yep

**Comment by szmarczak** [comment]
@Equidem wasn't sure about that solution so I'm still awaiting his reply
