### ISSUE TITLE
Invalid filename after Electron build

### ISSUE THREAD

**Issue by Stitch-cc** [apify/got-scraping#99]
Describe the bug
When initializing BayesianNetwork in the constructor of the HeaderGenerator class, __dirname is used, but after Electron is built, __dirname does not point to the same thing.

System information:
OS: win
Node.js version 18.16.0
Electron: 25.4.0

Additional context
![image](https://github.com/apify/got-scraping/assets/28957590/ca2380e4-388c-4520-8e6b-a53473336af4)

**Comment by B4nan** [comment]
Closing in favor of https://github.com/apify/fingerprint-suite/issues/212

This is exactly the same issue, no need to report it multiple times.
